### ISSUE TITLE
Thanks for the awesome crate!

### ISSUE THREAD

**Issue by mitchmindtree** [bluss/petulant-avenger-graphlibrary#1]
I couldn't find a contact so I thought I'd leave a message here.

Just wanted to say your `Graph` implementation has been incredibly useful and that I've learned a lot about graph data structures while using it over the past couple days! I've had a problem that I've been unsure of how to solve elegantly in Rust for quite a while - `Graph` turned out to be the perfect solution!

I've used it to create a directed, acyclic, DSP graph (aimed at simplifying design of complex audio DSP chains). Not sure if you'd be interested but [here's an example](https://github.com/RustAudio/dsp-chain/blob/master/examples/graph.rs#L34) of the usage and [here's the implementation](https://github.com/RustAudio/dsp-chain/blob/master/src/graph.rs#L9) where `petgraph::Graph` is used.

Anyways, enough rambling, thanks again :+1:

**Comment by bluss** [comment]
Wow that's awesome. Thank you! :smiley: 

Navigating how directed/undirected works might be a bit confusing in the current version -- hopefully that goes well. Basically some functionality is shared between undirected and directed graphs and some specific algos may treat all graphs as undirected. This was mainly to provide all algorithms to all kinds of graphs.
