### ISSUE TITLE
Use a Range<NodeIndex<Idx>> for less ambiguous Graph::add_edge args?

### ISSUE THREAD

**Issue by mitchmindtree** [bluss/petulant-avenger-graphlibrary#10]
Just an idea, might sound silly!

At the moment, a call to add_edge looks like this:
```rust
graph.add_edge(a, b, edge);
```
Although the user might be able to assume the direction of the edge they've added is the same as the ordering of the args, the user may feel the need to check the docs to be certain (I remember doing so).

Perhaps another possibility is to have the method take a `::std::ops::Range<NodeIndex<Ix>>` instead:
```rust
graph.add_edge(a..b, edge);
```

This is as ergonomic (same number of characters) and perhaps (imo) slightly more intuitive - the `Range` fields are called `start` and `end`, so there can be no ambiguity about the direction of the edge.

On the other hand, this might be trying to get a bit too fancy! Just an idea :+1:

**Comment by bluss** [comment]
That's far too cute, so it will not happen :smile: 

Isn't it ok to just have them in the current start, end or from, to order? It should be pretty consistent with other APIs that way.

**Comment by mitchmindtree** [comment]
Yeah it's totally fine, really! Just thought I'd throw it out there - I was perhaps blinded by the cuteness :smile_cat:

**Comment by bluss** [comment]
cuteness denied :-1: :scream:

**Comment by bluss** [comment]
hehe
