### ISSUE TITLE
`Graph::new/new_undirected` are not generic over `IndexType`

### ISSUE THREAD

**Issue by mitchmindtree** [bluss/petulant-avenger-graphlibrary#11]
Not sure if there is a reason behind this or if it's an oversight (or more probable - I'm missing something)?

I'm starting up a `rose_tree` crate that uses a `Graph` internally, and I just noticed this when I went to wrap `Graph::new()`. In both conrod and dsp-chain I've only ever used `Graph::with_capacity` so I haven't noticed until now.

**Comment by bluss** [comment]
It's intentional for now.. type parameter defaults can't help here yet (coming rust feature), so these are specific to allow ease of use. Use with_capacity for the generic interface.

**Comment by bluss** [comment]
Using u32 indices by is an unfortunate mistake I think. Maybe we can fix it down the line.

**Comment by bluss** [comment]
The default type parameter fallback feature is basically on hold, so I'm going to close this, we can't fix it.

`Graph::with_capacity` is fully generic and can create a graph of any type.
