### ISSUE TITLE
Iterator over the all edges of a GraphMap

### ISSUE THREAD

**Issue by contradictioned** [bluss/petulant-avenger-graphlibrary#16]
If I don't miss anything it is only possible to call `nodes()` to get an iterator over all nodes of a graph or ` `edges(from: N)` in order to get the edges incident to N.

Is there a special reason, that there is no iterator over *all* edges of a graph (in no specified order)?

**Comment by mitchmindtree** [comment]
@contradictioned there is the [`raw_edges` method](http://bluss.github.io/petulant-avenger-graphlibrary/doc/petgraph/graph/struct.Graph.html#method.raw_edges) - you could use that to produce a slice upon which you could call `.iter()` to produce an iterator over all edges. Does that suit your need?

**Comment by contradictioned** [comment]
@mitchmindtree unfortunateley this does not exist for a `GraphMap`...

**Comment by mitchmindtree** [comment]
Agh, apologies.

**Comment by contradictioned** [comment]
No problem, this hint was inspirational :D

**Comment by contradictioned** [comment]
Solved by #18
