### ISSUE TITLE
Breaking changes for version 0.2

### ISSUE THREAD

**Issue by bluss** [bluss/petulant-avenger-graphlibrary#27]
- [x] Fix #19
- [x] Fix element type of `GraphMap::all_edges()`
-  ~~Look at panic vs return option behavior of Graph methods?~~
- [x] ~~Remake Graph's edges() iterator methods, maybe #13, also #39~~ Actual change is #39 
- [x] Remove MinScored?
- [x] Remove IndexType::one, zero.
- [x] Fix neighbors #31 
- [x] Mark IndexType unsafe
- [x] Revise ESI and DEI for Graphmap's iterators

.

- ~~GraphMap::add_node, change return type to `()`, maybe?~~
- [x] GraphMap::add_edge, change return type to `Option<E>`
- [x] ~~Rename~~ Remove Graph::edges_both to edges_undirected
- [x] Rename Graph::without_edges -> externals
- [x] Undirected, Directed should be enums.

**Comment by bluss** [comment]
cc @mitchmindtree @sfackler  Register your thoughts about breaking changes to improve the crate here. Thanks!

**Comment by mitchmindtree** [comment]
@bluss what are your thoughts on the breaking changes suggested in #13 (particularly [this comment](https://github.com/bluss/petulant-avenger-graphlibrary/issues/13#issuecomment-150135464))? I've found it to be an awesome improvement for daggy, especially noticed after cleaning up conrod quite a bit (examples of use [here](https://github.com/mitchmindtree/conrod/blob/graphics_widgets/src/graph/mod.rs#L470-L613), throughout [here](https://github.com/mitchmindtree/conrod/blob/graphics_widgets/src/graph/algo.rs) and other places in the graph module).

The stuff you have listed there sounds good to me :) Going to sleep on it and might add some more thoughts tomorrow.

**Comment by bluss** [comment]
@mitchmindtree I'll have to try it out. My initial thoughts are that I want to keep the neighbors iterators and replace the edges iterators with the more general walker scheme. I think iterators need to be readily available, also for the general interface.


**Error handling**, current status:

- indexing with [GraphIndex], panic
- index_twice_mut, panic
- node_weight, edge_weight, Option
- edge_endpoints, Option
- neighbors(a), no error case (empty iter on out of bounds)
- remove_node, remove_edge Option
- add_edge panic

**Changes**

- Add `.edge(EdgeIndex) -> Option<&Edge>`  for generic source, target, weight access option-wise
- Add `.node(NodeIndex) -> Option<&Node>` same way
- Make `edge_endpoints`, `remove_node`, `remove_edge` all panic on index out of bounds.

This would be more consistent with [error conventions](https://github.com/rust-lang/rfcs/blob/master/text/0236-error-conventions.md). It's very panicky, but it's consistent with how other indexing containers work, for example, `Vec::remove(i)` will panic on out of bounds.

I'm not 100% convinced about the remove methods. Returning Option is nice, but it's so noisy.
