### ISSUE TITLE
Add StableGraph / a stable indices after deletion graph

### ISSUE THREAD

**Issue by bluss** [bluss/petulant-avenger-graphlibrary#38]

**Comment by bluss** [comment]
## Log

- Feasibility to use the "CompactVec" scheme, detailed in RustAudio/dsp-chain/issues/103 and [https://github.com/RustAudio/dsp-chain/issues/103#issuecomment-160322696](comment).

**Comment by bluss** [comment]
Draft PR: #42

**Comment by bluss** [comment]
Issue #25 will be needed too

**Comment by mitchmindtree** [comment]
Ahh sorry @bluss , I must have missed your log here.

> Internal trait work is equivalent to and exceeding what's needed to have Graph and StableGraph just be separate trait with an external, public trait instead

Remember that although it might seem just as verbose in petgraph itself, this trait work would make genericity in downstream creates like `daggy` much simpler.

> Requires the whole interface to be replicated in a private trait and implemented by each backend

Just out of curiousity, do you have this code still (maybe in some older commits on another branch)? All good if not, I should have paid closer attention at the time :)

**Comment by bluss** [comment]
> Remember that although it might seem just as verbose in petgraph itself, this trait work would make genericity in downstream creates like daggy much simpler.

I am doubtful. You can look how far I got before I drew conclusions, in the [stable-unification branch](https://github.com/bluss/petulant-avenger-graphlibrary/tree/stable-unification-2)

**Comment by mitchmindtree** [comment]
Hmmm this does look super complex...

It's a little different to what I had imagined - I still think I'd have opted for the extra Container type params on `Graph` itself despite the verbosity as the noise would be more contained within petgraph itself. In most downstream use-cases I imagine the type noise would get type-aliased down to nothing right away, for example both dsp-chain and conrod would look something like this.
```rust
type Graph = pg::Graph<Node, Edge, StableVec<Node>, Vec<Edge>, Directed, usize>;
```

Or more likely, petgraph and daggy would already have type aliases for `VecGraph` and `StableGraph`, i.e.
```rust
type Dag = daggy::StableDag<Node, Edge, usize>;
```

However, I can empathise with not wanting to over-parameterize in petgraph itself. I guess we can revisit the idea once (if?) we have some sort of HKT thing in the future :)

**Comment by bluss** [comment]
Parametrization is ok, although my favoured solution would be to have a marker type (and that seemed to work), so that it's only `Graph<..., Vector>` or `Graph<..., StableVector>`. Otherwise it just gets too messy to use, `Vec<Edge<E, Ix>>` is not so nice.
