### ISSUE TITLE
Some thoughts and ideas related to Graph.

### ISSUE THREAD

**Issue by mitchmindtree** [bluss/petulant-avenger-graphlibrary#4]
During my use of `Graph` in dsp-chain I've run into a few issues for which there don't yet seem to be any easy work-arounds and often I find myself resorting to unsafe code when there is probably a nicer solution possible within `Graph`'s API. Most instances revolve around gaining simultaneous mutable access to multiple different nodes/edges at once. Just thought I'd share some of these issues along with some thoughts and ideas on how they might be addressed.

Access to incoming edges
-----------------------------------

I've noticed that Graph provides two main methods for iterating over edges of a given node:

- `edges`: provides an iterator over the outgoing edges paired with their respective node indices.
- `edges_both`: provides an iterator over all edges paired with their respective node indices.

Here are some thoughts that came to mind:
- Perhaps `edges` could take a `Direction` argument so that a user may iterate over either direction, rather than only `Outgoing`?
- Perhaps it would be useful to provide `edges_mut` and `edges_both_mut` variations?
- Maybe `edges_undirected` (instead of `edges_both`) would be more consistent with `neighbors_undirected` and `find_edge_undirected`?

Simultaneous mutable access to a node and its edges.
-------------------------------------------------------------------------

There are a few variations on this problem, the two that I've run into are:

- Needing both mutable access to a node weight and immutable access to its incoming edge weights simultaneously.
- Needing both immutable access to a node weight and mutable access to its outgoing edge weights simultaneously.

The exact use case within dsp-chain is: (during a reverse dfs) each node must be able to read from each of its incoming edge's buffers so that it may sum them to its own buffer. Once it has rendered its own buffer, it then writes the result to each of its outgoing edges' buffers. This must all be achieved without allocating any new intermediate buffers.

In the API's current state I'm unsure of how to get around this without unsafe code. I imagine it should be possible to expose a safe interface to this use-case so that the above examples look something like:

```Rust
// Mutable access to a node weight and immutable access to its incoming edge weights simultaneously.
graph.node_mut_with_edges(node_idx, pg::Incoming, |node_weight_mut, edge_weights| {
    for edge_weight in edge_weights {
        // do stuff with node_weight_mut and edge_weight....
    }
})

// Immutable access to a node weight and mutable access to its outgoing edge weights simultaneously.
graph.node_with_edges_mut(node_idx, pg::Outgoing, |node_weight, edge_weights_mut| {
    for edge_weight_mut in edge_weights_mut {
        // do stuff with node_weight and edge_weight_mut...
    }
});
```

Pair indexing
-----------------

It would be nice to be able to index into the graph twice at once, i.e. perhaps by allowing indexing the `Graph` with tuples.

```Rust
let (a_weight, b_weight) = &mut graph[(a, b)];
```

I noticed that you have a private `index_twice` function in the graph module already - perhaps there's a reason you've avoided exposing it? I guess one problem with this is that the returned references are always either 1. both immutable or 2. both mutable, without exposing an option for combinations of the two.

Anyway, apologies for the lengthy issue! These are currently things I'm dodging with unsafe, but just thought I'd come to the source, share my experience and perhaps land a nicer solution closer to home - let me know your thoughts when you get a chance :) Also, if there are already nice solutions to any of the above that I might have missed, please feel free to share!

**Comment by bluss** [comment]
Thank you for writing this, it's very valuable!

I think almost all of it can be addressed. Graphs and mutability are tricky, I'm already happy with how the Dfs type allows you to traverse it without an active borrow. But I understand you need more than that.

I've imagined that in some cases you may have to use closure-callback based traversals rather than iterators -- your sketch of this is a good example of something I think we can do.

I knew edge iterators were inconsistent, but I didn't need them yet, so they have just stayed like they were. I'll definitely update these.

`index_twice` is just a function I need for indexing a slice twice -- of course the idea can be extended to the graph.

**Comment by bluss** [comment]
I'll start with the easy parts -- edges_directed() is in 0.1.7.

**Comment by bluss** [comment]
Look at the [index twice branch](https://github.com/bluss/petulant-avenger-graphlibrary/commits/index-twice)! Adding this “simple” method (not so simple) allows you do very much with safe code. 

This is experimental so far.

[Look at the testcase](https://github.com/bluss/petulant-avenger-graphlibrary/blob/374e3272268391727117757814643ae492587c1b/tests/ograph.rs#L640-L688) I added which shows how to read & mutate edges and nodes at the same time, as long as they are disjoint.

As you can see, all the iteration has to be "manual" because we can't give a borrow of the graph to an iterator. But it works..

**Comment by bluss** [comment]
Added the edge walker to make the testcase much nicer to write.

**Comment by mitchmindtree** [comment]
Ohhh my! Awesome work! That `edge_walker`/`index_twice` combo makes for a beautiful stroll :+1:

**Comment by bluss** [comment]
Thank you for the ideas for this! I'm cleaning it up & will merge to master today. I'm quite excited it turned out so nice.

**Comment by bluss** [comment]
Published in 0.1.8. Documented & changed some names. I think this turned out great so far. index_twice is more than twice as cool as indexing twice!

**Comment by mitchmindtree** [comment]
> twice as nice*

Awesome! Well, I guess that addresses this entire issue! Going to close, but feel free to re-open if you feel there is still more related work to be done :+1:

**Comment by bluss** [comment]
@mitchmindtree I've been puzzling over that “reverse dfs” order you said you needed. I don't know your package, but maybe you're thinking of topological order? That's used when you have a DAG and need to visit all dependencies before you visit their consumers.

**Comment by mitchmindtree** [comment]
Oh no need to puzzle over it - you're right, what I was after what the topological order so that I could visit all dependencies before their consumers :+1: I didn't know what a topological sort was until soon after I asked you about the reverse dfs :)

In the end, my dsp-chain is working nicely by:
1. Doing a DFS through the graph from the master node with the edge directions reversed ([here](https://github.com/RustAudio/dsp-chain/blob/master/src/graph.rs#L145)).
2. Collecting and storing the indices in their visit order.
3. Iterating over the dfs_visit_order (this is topological order, right?) in reverse when audio is requested ([here](https://github.com/RustAudio/dsp-chain/blob/master/src/graph.rs#L334)).

I noticed that there is an `algo::toposort` function, however it takes a `&Graph` rather than a `&G where G: Visitable` which meant I was unable to use the `visit::Reversed` wrapper as I could with `Dfs` (I was meaning to mention this to you, but hadn't got around to it yet). Would it be possible for `toposort` to take a generic `Visitable` type rather than a `Graph`?

**Comment by bluss** [comment]
I don't think that's topological order.

I was thinking of this graph:

```
A -> B
B -> C
A -> C
```

Only topo order is A, B, C

A reverse dfs from C could visit either B or A first.

Yes, toposort could be made more generic, but I think you can just reverse the topo order you get.

**Comment by mitchmindtree** [comment]
@bluss ahh you're right, apologies, for some reason I thought a starting index  was needed for a toposort and that in turn the edge directions would affect whether or not some nodes were visited (like in a Dfs) - I realise now that doesn't make sense!

Thanks for the simple example, it has made me realise that I do indeed need a toposort instead of a reverse dfs (I just hadn't yet come across a situation in which it would break). I'll have a go at using the toposort and let you know how it works out :)

**Comment by mitchmindtree** [comment]
Just [made the changes](https://github.com/RustAudio/dsp-chain/pull/116/files) and she seems to be working beautifully! Also quite a bit neater :) Once again, many thanks!

**Comment by bluss** [comment]
Nice! As I said, I want to make this a bit more general, so that you can regenerate the order without having to allocate a new vec. Do you have any performance sensitive parts of your library? I was wondering if allocations might be a hurdle somewhere. The graph algorithms generally allocate at least a node bitmap to track the visited list.

**Comment by mitchmindtree** [comment]
A non-allocating option would definitely be appreciated! I'd love for dsp-chain to be a prime option for real-time audio, so avoiding dynamic allocation, locking, etc where possible are all big priorities.

**Comment by bluss** [comment]
Ok. Which operations? I'm mostly thinking of having the option to use preallocated structures for visit map and so on.

**Comment by mitchmindtree** [comment]
The two algos that I'm currently using are `is_cyclic_directed` (to [check](https://github.com/RustAudio/dsp-chain/blob/master/src/graph.rs#L166) whether or not adding an edge would create a cycle) and `toposort` (to prepare the visit order each time an edge is added).

**Comment by bluss** [comment]
Toposort improvements are now issue  #5

Fun fact: is_cyclic_directed just computes toposort and checks that it gets a valid topo order for all nodes, if this fails, the graph is cyclic.
