### ISSUE TITLE
Allow reusing allocated state for toposort

### ISSUE THREAD

**Issue by bluss** [bluss/petulant-avenger-graphlibrary#5]
Toposort needs a visit map and maybe a stack to put items to visit. Allow reusing these instead of allocating them anew every time.

**Comment by bluss** [comment]
- [incremental cycle detection DAG](https://www.google.com/search?q=incremental+cycle+detection+DAG)

**Comment by mitchmindtree** [comment]
Perhaps it'd also be nice to expose a `Toposort` type, who managed its own map/stack - similar to how there are `Dfs` and `Bfs` types that manage their own stacks and can be re-used.

**Comment by bluss** [comment]
Fixed by #9 in that fashion. The incremental topo order / cycle detection problem is much harder (and requires more datastructures).
