### ISSUE TITLE
Handle the alternate flag in Dot's debug impl

### ISSUE THREAD

**Issue by sfackler** [bluss/petulant-avenger-graphlibrary#51]
`Dot`'s `Debug` implementation currently always formats nodes and edge weights with `{:?}`, but this can result in unfortunate graphviz output when labels end up being long single line things. It would be nice if the implementation would forward the alternate flag (`#` e.g. `{:#?}`) to the node and edge formatters.

**Comment by bluss** [comment]
It makes sense. We'll do this, and bump the requirement to Rust 1.5 (finally we have Formatter::alternate()!).

There's a ton of complexity in graphviz and `Dot` is for the simple use cases and debugging — the crate `dot` will be recommended / required to handle advanced formatting. I've been looking at how to best integrate with it.

**Comment by sfackler** [comment]
Thanks!
