### ISSUE TITLE
Unexpected extra nodes

### ISSUE THREAD

**Issue by dimbleby** [bluss/petulant-avenger-graphlibrary#57]
```rust
use petgraph::Graph;

fn main() {
    let gr = Graph::<i32, ()>::from_edges(&[(2, 3)]);
    assert_eq!(gr.node_count(), 2);
}

thread '<main>' panicked at 'assertion failed: `(left == right)` (left: `4`, right: `2`)', src/main.rs:7
```

Looks like nodes 0 and 1 are implicitly added.

Is this a bug, or a feature?  

If a feature then it's one that I found surprising.  Did I miss something in the documentation?

**Comment by bluss** [comment]
It's a feature. Node indices for `Graph` are a compact range (no holes) from 0 to *n* - 1 (inclusive) where *n* is the number of nodes. [doc](http://bluss.github.io/petulant-avenger-graphlibrary/doc/petgraph/graph/struct.Graph.html#tradeoffs-with-indices)

**Comment by dimbleby** [comment]
Aha, the "2" and "3" are only node indices, not actual `N`s.  I see.

Working As Designed then.  

Is there a way to do what I was hoping to do: which is to construct a graph by adding edges between `N`s and having the library automatically add new nodes as it sees them?  Or must I do some preliminary work myself to build up my own map of node -> node index, and then construct the graph only in terms of node indices?

Either way, please feel free to close out the issue.

**Comment by bluss** [comment]
`Graph` is the primary type in petgraph, and it doesn't have a helper for that; I've contemplated adding one (a GraphBuilder), since it's so common.
