### ISSUE TITLE
Topological iterator for subgraph.

### ISSUE THREAD

**Issue by WaDelma** [bluss/petulant-avenger-graphlibrary#63]
It would be nice if there was way to traverse directed graph topologically starting from certain node.

**Comment by WaDelma** [comment]
Also why topo doesn't have way to tell from which edge we came from?

**Comment by bluss** [comment]
Sounds nice. Topo is quite limited. You don't really come from a particular edge, any of the incoming edges for a node are equally valid, aren't they?

**Comment by WaDelma** [comment]
It wouldn't for topological traversal for the whole graph, but if you topologically traverse subgraph starting from node there is incoming edges that aren't from that subgraph.
(That also answers why it doesn't tell incoming edges as there wasn't reason for it before :P)
Btw I have added method `with_node` for `Topo` locally, but I don't have tests for it.

**Comment by bluss** [comment]
Sounds good. Maybe `from_node` should be the name? I especially appreciate if you use quickcheck to write the tests.

**Comment by WaDelma** [comment]
Yeah I actually had it `from_node`, dunno why I wrote it that way there.    
I have added quickcheck tests for whole graph `Topo` usage and when trying to write one for one node usage I realised that current algorithm doesn't work with it.    
Basically it checks that if there is only incoming edges from it is next in order, but when we don't visit whole graph that doesn't work. Easiest way to fix that would be just add additional `Vec` for non-visited nodes and when `tovisit` is echausted start going that through.    
Also for the quickcheck test for one node `Topo` I had to reimplement `Bfs` so I could extract subgraph that can be get to via the node.

**Comment by bluss** [comment]
Very good point. 

And yes we need a more flexible dfs visitor (#37).

I'm not sure how to best solve it actually, maybe if there's a filter that can say if an edge should be considered or not?

**Comment by WaDelma** [comment]
Btw using `Vec` as a stack for not visited nodes wasn't actually sufficient: I had to use `VecDeque` for queue. Quickcheck tests catched that problem only sometimes.

**Comment by WaDelma** [comment]
Whoops.

**Comment by bluss** [comment]
@domenkozar Hi, could you report a new issue about, and explain with an example what you mean is missing?

**Comment by domenkozar** [comment]
https://github.com/petgraph/petgraph/issues/661
