### ISSUE TITLE
Add `walk_neighbors_directed`

### ISSUE THREAD

**Issue by mitchmindtree** [bluss/petulant-avenger-graphlibrary#7]
This would be the same as `walk_edges_directed`, but `WalkNeighbors` would return the neighboring `NodeIndex`s, rather than the indices of the edges connecting them.

Similar to `neighbors_directed` iterator, but doesn't borrow the graph.

**Comment by bluss** [comment]
The edge walker has been improved to allow this already, see [`next_neighbor()`](http://bluss.github.io/petulant-avenger-graphlibrary/doc/petgraph/graph/struct.WalkEdges.html#method.next_neighbor)

**Comment by mitchmindtree** [comment]
Oh nice! Thank yee once again :+1:
